apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argo-workflows
  name: workflow-controller-configmap
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: argo-artifacts
      endpoint: argo-minio:9000
      insecure: true
      accessKeySecret:
        name: argo-custom
        key: minio-access-key
      secretKeySecret:
        name: argo-custom
        key: minio-secret-key
  executor: |
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
  metricsConfig: |
    disableLegacy: true
    enabled: true
    path: /metrics
    port: 9090
  persistence: |
    connectionPool:
      maxIdleConns: 100
      maxOpenConns: 0
      connMaxLifetime: 0s
    nodeStatusOffLoad: true
    archive: true
    archiveTTL: 7d
    postgresql:
      host: argo-postgresql
      port: 5432
      database: argo-postgres
      tableName: argo_workflows
      userNameSecret:
        name: argo-custom
        key: argo-postgres-user
      passwordSecret:
        name: argo-custom
        key: argo-postgres-pass
