apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argo-server
spec:
  rules:
  - host: "%{host}"
    http:
      paths:
        - path: /
          backend:
            serviceName: argo-server
            servicePort: web
