apiVersion: v1
kind: Secret
metadata:
  name: "argo-custom"
data:
  # Result of: echo -n 'example' | base64
  "minio-access-key": "%{minio-access-key}"
  "minio-secret-key": "%{minio-secret-key}"
  "argo-postgres-user": "%{argo-postgres-user}"
  "argo-postgres-pass": "%{argo-postgres-pass}"
