---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-chart-kubeview
spec:
  template:
    spec:
      containers:
      - name: kubeview
        env:
        - name: NAMESPACE_SCOPE
          value: prod-kubeview
